---
- name: Gather IOS L2 interfaces in access mode and configure for 802.1x
  hosts: testing
  gather_facts: no

  ##############################################################
  # TASKS REQUIRED TO CONFIGURE SWITCHPORTS FOR RADIUS IBNS 1.0 #
  ##############################################################

  # Gather Layer 2 interface facts. This will only gather information for access and trunk interfaces.
  # Includes information such as switchport mode, if access the VLAN, if trunk the VLANs on the trunk, interface name, etc.
  tasks:
  - name: gather IOS facts for layer 2 interfaces
    ios_facts:
      gather_network_resources: l2_interfaces

  ########
  # THIS SECTION WILL REMOVE PRE-EXISTING FILES THAT WE WILL CREATE LATER
  ########

  #We will save the interface facts into a JSON later, so we will delete the JSON file if it already exists
  - name: Delete {{inventory_hostname}}_facts.JSON file if it exists
    file:
      path: /home/tobarows/gather_facts_switches/{{inventory_hostname}}_facts.json
      state: absent
  
  #We will filter out only access swithports later and save it to a file, so we will delete that file if it already exists
  - name: Delete {{inventory_hostname}}_access_switchport.txt file if it exists
    file:
      path: /home/tobarows/gather_facts_switches/{{inventory_hostname}}_facts.json
      state: absent

  #We will save the pre-RADIUS configuration to a backup file, so we will delete that backup file if it already exists
  - name: Delete {{inventory_hostname}}_pre_radius_backup.cfg file if it exists
    file:
      path: /home/tobarows/gather_facts_switches/{{inventory_hostname}}_pre_radius_backup.cfg
      state: absent

  #We will save the post-RADIUS configuration to a backup file, so we will delete that backup file if it already exists
  - name: Delete {{inventory_hostname}}_post_radius_backup.cfg file if it exists
    file:
      path: /home/tobarows/gather_facts_switches/{{inventory_hostname}}_post_radius_backup.cfg
      state: absent

  ########
  # THIS SECTION PERFORMS THE ACTUAL TASK OF GATHERING INTERFACE INFO, PARSING ACCESS PORTS, AND CONFIGURING FOR RADIUS
  ########

  # Create a pretty-formatted JSON file that will save the l2_interfaces obj. This file is saved to disk. 
  - name: Create formatted JSON file that contains ALL layer 2 interfaces.
    copy:
      content: |
        {{ ansible_network_resources['l2_interfaces'] | to_nice_json }}
      dest: /home/tobarows/gather_facts_switches/{{inventory_hostname}}_facts.json

  # In the next task we will be filtering layer 2 interfaces and saving them to a file. Here we create that file
  - name: Create a new file
    file:
      path: /home/tobarows/gather_facts_switches/{{inventory_hostname}}_access_switchport.txt
      state: touch

  # In this tasks we put lines into a text file for each interface in access mode. 
  # lineinfile module lets us put a line in a file
  # line parameter is the text to place in file
  # insertafter parameter is crucially important as it tells ansible to append the line
  # dest is self-explainitory, its the destination file
  # We delegate this task to localhost
  # and MOST IMPORTANTLY we reference the items in l2_interfaces structure
  # only WHEN the item.mode (interfaces mode) is defined, and is set to access
  # I found that some interfaces will appear as l2 but not have mode key defined, leading to errors. 
  # This is why we make sure it exists first.
  - name: List interfaces that are access mode
    lineinfile:
      line: "Interface: {{item.name}} is set to {{ item.mode }} on VLAN:{{item.access.vlan}}"
      insertafter: EOF  
      dest: /home/tobarows/gather_facts_switches/{{inventory_hostname}}_access_switchport.txt
    delegate_to: 127.0.0.1
    with_items: "{{ ansible_network_resources['l2_interfaces'] }}"
    when: item.mode is defined and item.mode == "access"
  
  # We want to backup the running configuration on the switch before configuring RADIUS 
  - name: Backup IOS config
    ios_config:
      backup: yes
      backup_options:
        filename: "{{inventory_hostname}}_pre_radius_backup.cfg"
        dir_path: /home/tobarows/gather_facts_switches/

  # This task actually configures switchports for RADIUS IBNS 1.0
  - name: Configure access interfaces for 802.1x
    #ios_config module allows us to config IOS devices
    ios_config:
      #add these lines to the configuration
      lines:
        - description ACCESS_INTERFACE
        - authentication event fail action next-method
          #We reference the predefined vlan for the switchport
        - authentication event server dead action authorize vlan {{item.access.vlan}}
        - authentication event server dead action authorize voice
        - authentication event server alive action reinitialize
        - authentication host-mode multi-auth
        - authentication open
        - authentication order mab dot1x
        - authentication priority dot1x mab
        - authentication port-control auto
        - authentication periodic
        - authentication timer reauthenticate server
        - authentication violation restrict
        - mab
        - dot1x pae authenticator
        - dot1x timeout tx-period 10
      # We configure the above lines under INTERFACE sub config mode. 
      # The interface we configure on in item.name, which is the current l2 access interface in the list of items
      parents: "interface {{ item.name }}"
      # Save the running-config when we finish
      save_when: modified
    #We iterate over the l2 interfaces to apply config to (see next comment
    with_items: "{{ ansible_network_resources['l2_interfaces'] }}"
    #each interface where mode is defined and the mode is access mode.
    when: item.mode is defined and item.mode == "access"

  #We issue the show run command and save the output to a variable named config
  - name: Issue a show run and save config
    ios_command:
      commands: show run
    register: config

  #Take the config variable that contains the show run and write it to file
  - name: Save post RADIUS config to file. 
    copy:
      content: "{{ config.stdout | replace('\\n','\n') }}"
      dest: /home/tobarows/gather_facts_switches/{{inventory_hostname}}_post_radius_backup.cfg
